### ISSUE TITLE
KeyError at /bom/

### ISSUE THREAD

**Issue by LudoNash** [mpkasp/indabom#52]
Hi there, 

I am looking forward to testing indabom as it seems like a great product and fits my needs. 

I am not a developer and have limited coding experience. I have followed the instructions, watch the video and get an error at the end after setting up my organization. Below is the text i get. 

Looking forward to your feedback, thank you. 
<img width="1024" alt="Screenshot 2023-04-26 at 19 46 34" src="https://user-images.githubusercontent.com/105787556/234731880-f2c7a5ee-5c58-4923-ad1f-68f3637fce6a.png">

Traceback (most recent call last):
  File "/Users/ludoroche/repos/inda_bom/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner response = get_response(request)
  File "/Users/ludoroche/repos/inda_bom/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/ludoroche/repos/inda_bom/venv/lib/python3.10/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapper_view return view_func(request, *args, **kwargs)
  File "/Users/ludoroche/repos/inda_bom/venv/lib/python3.10/site-packages/bom/views/views.py", line 146, in home
    enable_autocomplete = settings.BOM_CONFIG['admin_dashboard']['enable_autocomplete']

Exception Type: KeyError at /bom/
Exception Value: 'admin_dashboard'

**Comment by LudoNash** [comment]
modified line 278 of views.py with 
page_size = settings.BOM_CONFIG.get('admin_dashboard', {}).get('page_size', 25) # Replace 25 with your desired default page size

**Comment by mpkasp** [comment]
Thank you!
